### ISSUE TITLE
[Feature Request] Adding Internet Dowlink | Uplink usuage.

### ISSUE THREAD

**Issue by shirshak55** [GijsGoudzwaard/nova-system-resources#1]
Thanks for package. It is just a feature request :)

**Comment by GijsGoudzwaard** [comment]
After some thought I've come to the conclusion that I won't implement this feature. Calculating the internet speed would require files to be downloaded / uploaded constantly which I don't think is a good idea for a small package like this.

**Comment by shirshak55** [comment]
@GijsGoudzwaard i didn't mean that. I mean like showing current up and down which many unix socket do . Tools like iftop etc can show that.

**Comment by shirshak55** [comment]
hmm you are understanding like showing overall bandwidth available but i mean showing currently used bandwidth.
