### ISSUE TITLE
Call to undefined method GijsG\SystemResources\SystemResources::boot()

### ISSUE THREAD

**Issue by cord** [GijsGoudzwaard/nova-system-resources#10]
good stuff!

However on latest nova + laravel I get following error

`Call to undefined method GijsG\SystemResources\SystemResources::boot()`

any idea how to solve it?

**Comment by GijsGoudzwaard** [comment]
Which version are you using? My nova is on `1.3.1` and laravel on `5.7.*` and I do not get this error.

**Comment by cord** [comment]
same here, but forgot to mention am using Spark latest as well - maybe this is causing issues?

```json
"require": {
        "php": "^7.1.3",
        "cendekia/nova-setting-tool": "^0.0.3",
        "divineomega/array_undot": "^2.0",
        "doctrine/dbal": "^2.8",
        "fideloper/proxy": "^4.0",
        "gijsg/system-resources": "dev-master",
        "grimthorr/laravel-user-settings": "^2.1",
        "krowinski/tinyid": "^1.1",
        "laravel/cashier": "~7.0",
        "laravel/framework": "5.7.*",
        "laravel/nova": "~1.0",
        "laravel/spark-aurelius": "*@dev",
        "laravel/tinker": "^1.0",
        "league/csv": "^9.0",
        "mpociot/vat-calculator": "^2.2",
        "spatie/laravel-permission": "^2.29",
        "vyuldashev/nova-permission": "^1.4"
    },
```

**Comment by cord** [comment]
some details:
`
Symfony\Component\Debug\Exception\FatalThrowableError 
…/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php60
`

**Comment by GijsGoudzwaard** [comment]
Where are you calling `GijsG\SystemResources\SystemResources`? It should only be called in the `NovaServiceProvder` within the `cards` method as shown in the [readme](https://github.com/GijsGoudzwaard/nova-system-resources#installation).

**Comment by cord** [comment]
:man_facepalming:

thanks for guiding me :clap:
