### ISSUE TITLE
Error 500 in linux server

### ISSUE THREAD

**Issue by wemersonrv** [GijsGoudzwaard/nova-system-resources#12]
Hello. I'm getting Error 500 on a ubuntu server with nginx.

systemResources:1 GET https://maiscontrol.maispostos.com.br/nova-vendor/systemResources/ram 500
(anonymous) @ systemResources:1
e.exports @ systemResources:1
e.exports @ systemResources:1
Promise.then (async)
o.request @ systemResources:1
o.(anonymous function) @ systemResources:1
(anonymous) @ systemResources:1
i @ systemResources:1
mounted @ systemResources:1
we @ vendor.js?id=9e454f3261418eb9bca1:1
insert @ vendor.js?id=9e454f3261418eb9bca1:1
x @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t._update @ vendor.js?id=9e454f3261418eb9bca1:1
n @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.get @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.run @ vendor.js?id=9e454f3261418eb9bca1:1
Ce @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
Gt @ vendor.js?id=9e454f3261418eb9bca1:1
Promise.then (async)
Ut @ vendor.js?id=9e454f3261418eb9bca1:1
ee @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.update @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.lt.notify @ vendor.js?id=9e454f3261418eb9bca1:1
set @ vendor.js?id=9e454f3261418eb9bca1:1
Ee.set @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
z @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
t.(anonymous function) @ vendor.js?id=9e454f3261418eb9bca1:1
r @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
Promise.then (async)
r @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
e @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
created @ vendor.js?id=9e454f3261418eb9bca1:1
we @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t._init @ vendor.js?id=9e454f3261418eb9bca1:1
a @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
init @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
d @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t._update @ vendor.js?id=9e454f3261418eb9bca1:1
n @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.get @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.run @ vendor.js?id=9e454f3261418eb9bca1:1
Ce @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
Gt @ vendor.js?id=9e454f3261418eb9bca1:1
Promise.then (async)
Ut @ vendor.js?id=9e454f3261418eb9bca1:1
ee @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.update @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t.$forceUpdate @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
c @ vendor.js?id=9e454f3261418eb9bca1:1
e @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
u @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
setTimeout (async)
mi @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
requestAnimationFrame (async)
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
requestAnimationFrame (async)
pi @ vendor.js?id=9e454f3261418eb9bca1:1
L @ vendor.js?id=9e454f3261418eb9bca1:1
bi @ vendor.js?id=9e454f3261418eb9bca1:1
remove @ vendor.js?id=9e454f3261418eb9bca1:1
A @ vendor.js?id=9e454f3261418eb9bca1:1
b @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t._update @ vendor.js?id=9e454f3261418eb9bca1:1
n @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.get @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.run @ vendor.js?id=9e454f3261418eb9bca1:1
Ce @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
Gt @ vendor.js?id=9e454f3261418eb9bca1:1
Promise.then (async)
Ut @ vendor.js?id=9e454f3261418eb9bca1:1
ee @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t.$nextTick @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
y @ app.js?id=19fb4a6ed48aba1680e2:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
e.(anonymous function) @ app.js?id=19fb4a6ed48aba1680e2:1
o @ app.js?id=19fb4a6ed48aba1680e2:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
Promise.then (async)
o @ app.js?id=19fb4a6ed48aba1680e2:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
t @ app.js?id=19fb4a6ed48aba1680e2:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
l @ app.js?id=19fb4a6ed48aba1680e2:1
f @ vendor.js?id=9e454f3261418eb9bca1:1
r @ vendor.js?id=9e454f3261418eb9bca1:1
r @ vendor.js?id=9e454f3261418eb9bca1:1
ht @ vendor.js?id=9e454f3261418eb9bca1:1
_t.confirmTransition @ vendor.js?id=9e454f3261418eb9bca1:1
_t.transitionTo @ vendor.js?id=9e454f3261418eb9bca1:1
e.push @ vendor.js?id=9e454f3261418eb9bca1:1
Dt.push @ vendor.js?id=9e454f3261418eb9bca1:1
y @ vendor.js?id=9e454f3261418eb9bca1:1
e @ vendor.js?id=9e454f3261418eb9bca1:1
Yr.e._withTask.o._withTask @ vendor.js?id=9e454f3261418eb9bca1:1
systemResources:1 GET https://maiscontrol.maispostos.com.br/nova-vendor/systemResources/cpu 500
(anonymous) @ systemResources:1
e.exports @ systemResources:1
e.exports @ systemResources:1
Promise.then (async)
o.request @ systemResources:1
o.(anonymous function) @ systemResources:1
(anonymous) @ systemResources:1
i @ systemResources:1
mounted @ systemResources:1
we @ vendor.js?id=9e454f3261418eb9bca1:1
insert @ vendor.js?id=9e454f3261418eb9bca1:1
x @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t._update @ vendor.js?id=9e454f3261418eb9bca1:1
n @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.get @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.run @ vendor.js?id=9e454f3261418eb9bca1:1
Ce @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
Gt @ vendor.js?id=9e454f3261418eb9bca1:1
Promise.then (async)
Ut @ vendor.js?id=9e454f3261418eb9bca1:1
ee @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.update @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.lt.notify @ vendor.js?id=9e454f3261418eb9bca1:1
set @ vendor.js?id=9e454f3261418eb9bca1:1
Ee.set @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
z @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
t.(anonymous function) @ vendor.js?id=9e454f3261418eb9bca1:1
r @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
Promise.then (async)
r @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
e @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
created @ vendor.js?id=9e454f3261418eb9bca1:1
we @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t._init @ vendor.js?id=9e454f3261418eb9bca1:1
a @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
init @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
d @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t._update @ vendor.js?id=9e454f3261418eb9bca1:1
n @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.get @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.run @ vendor.js?id=9e454f3261418eb9bca1:1
Ce @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
Gt @ vendor.js?id=9e454f3261418eb9bca1:1
Promise.then (async)
Ut @ vendor.js?id=9e454f3261418eb9bca1:1
ee @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.update @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t.$forceUpdate @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
c @ vendor.js?id=9e454f3261418eb9bca1:1
e @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
u @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
setTimeout (async)
mi @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
requestAnimationFrame (async)
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
requestAnimationFrame (async)
pi @ vendor.js?id=9e454f3261418eb9bca1:1
L @ vendor.js?id=9e454f3261418eb9bca1:1
bi @ vendor.js?id=9e454f3261418eb9bca1:1
remove @ vendor.js?id=9e454f3261418eb9bca1:1
A @ vendor.js?id=9e454f3261418eb9bca1:1
b @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t._update @ vendor.js?id=9e454f3261418eb9bca1:1
n @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.get @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.Ne.run @ vendor.js?id=9e454f3261418eb9bca1:1
Ce @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ vendor.js?id=9e454f3261418eb9bca1:1
Gt @ vendor.js?id=9e454f3261418eb9bca1:1
Promise.then (async)
Ut @ vendor.js?id=9e454f3261418eb9bca1:1
ee @ vendor.js?id=9e454f3261418eb9bca1:1
I3G/.t.$nextTick @ vendor.js?id=9e454f3261418eb9bca1:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
y @ app.js?id=19fb4a6ed48aba1680e2:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
e.(anonymous function) @ app.js?id=19fb4a6ed48aba1680e2:1
o @ app.js?id=19fb4a6ed48aba1680e2:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
Promise.then (async)
o @ app.js?id=19fb4a6ed48aba1680e2:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
t @ app.js?id=19fb4a6ed48aba1680e2:1
(anonymous) @ app.js?id=19fb4a6ed48aba1680e2:1
l @ app.js?id=19fb4a6ed48aba1680e2:1
f @ vendor.js?id=9e454f3261418eb9bca1:1
r @ vendor.js?id=9e454f3261418eb9bca1:1
r @ vendor.js?id=9e454f3261418eb9bca1:1
ht @ vendor.js?id=9e454f3261418eb9bca1:1
_t.confirmTransition @ vendor.js?id=9e454f3261418eb9bca1:1
_t.transitionTo @ vendor.js?id=9e454f3261418eb9bca1:1
e.push @ vendor.js?id=9e454f3261418eb9bca1:1
Dt.push @ vendor.js?id=9e454f3261418eb9bca1:1
y @ vendor.js?id=9e454f3261418eb9bca1:1
e @ vendor.js?id=9e454f3261418eb9bca1:1
Yr.e._withTask.o._withTask @ vendor.js?id=9e454f3261418eb9bca1:1
2systemResources:1 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (systemResources:1)
    at e.exports (systemResources:1)
    at XMLHttpRequest.m.(anonymous function) (https://maiscontrol.maispostos.com.br/nova-api/scripts/systemResources:1:247455)

**Comment by GijsGoudzwaard** [comment]
Can you post the actual PHP error from the logs?

**Comment by wemersonrv** [comment]
> Can you post the actual PHP error from the logs?

Yeah, right! 

Follow the log:

`[2019-04-10 11:36:35] local.ERROR: shell_exec() has been disabled for security reasons {"userId":1,"exception":"[object] (ErrorException(code: 0): shell_exec() has been disabled for security reasons at /home/gestor/webapps/mais-control/vendor/gijsg/system-resources/src/Adapters/LinuxSystemResources.php:21)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'shell_exec() ha...', '/home/gestor/we...', 21, Array)
#1 /home/gestor/webapps/mais-control/vendor/gijsg/system-resources/src/Adapters/LinuxSystemResources.php(21): shell_exec('free')
#2 /home/gestor/webapps/mais-control/vendor/gijsg/system-resources/src/Adapters/SystemResources.php(84): GijsG\\SystemResources\\Adapters\\LinuxSystemResources->__construct()
#3 /home/gestor/webapps/mais-control/vendor/gijsg/system-resources/src/Adapters/SystemResources.php(41): GijsG\\SystemResources\\Adapters\\SystemResources->getDriver()
#4 /home/gestor/webapps/mais-control/vendor/gijsg/system-resources/src/SystemResources.php(66): GijsG\\SystemResources\\Adapters\\SystemResources->ramResources()
#5 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): GijsG\\SystemResources\\SystemResources->ram()
#6 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(GijsG\\SystemResources\\SystemResources), 'ram')
#7 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#8 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#9 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /home/gestor/webapps/mais-control/_nova_local_repo/src/Http/Middleware/Authorize.php(18): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /home/gestor/webapps/mais-control/_nova_local_repo/src/Http/Middleware/BootTools.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\BootTools->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/gestor/webapps/mais-control/_nova_local_repo/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/gestor/webapps/mais-control/_nova_local_repo/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#43 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#44 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#45 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#46 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#47 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/gestor/webapps/mais-control/_nova_local_repo/src/Http/Middleware/ServeNova.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/gestor/webapps/mais-control/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#68 /home/gestor/webapps/mais-control/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#69 /home/gestor/webapps/mais-control/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#70 {main}
"} 
`

**Comment by GijsGoudzwaard** [comment]
Inside your `php.ini` you might have disabled the `shell_exec` function. To enable this remove `shell_exec` from your `disabled_functions` property in the `php.ini` file.

It is possible that your hosting provider has this option disabled by default and will override your `php.ini`. In that case you won't be able to use this package.

**Comment by wemersonrv** [comment]
> Inside your `php.ini` you might have disabled the `shell_exec` function. To enable this remove `shell_exec` from your `disabled_functions` property in the `php.ini` file.
> 
> It is possible that your hosting provider has this option disabled by default and will override your `php.ini`. In that case you won't be able to use this package.

Tx @GijsGoudzwaard . It works now.
