### ISSUE TITLE
[Question] What is the life cycle of the data?

### ISSUE THREAD

**Issue by mediabc** [GijsGoudzwaard/nova-system-resources#15]
Does the data have a lifetime limits? 

Or they are store forever in cache store (file or Redis)?

**Comment by GijsGoudzwaard** [comment]
A maximum of 12 integers ranging from 0 to 100 per resource (so 24 for CPU and RAM) are stored forever using the `file` cache driver.

You can see the implementation here:
https://github.com/GijsGoudzwaard/nova-system-resources/blob/master/src/Adapters/SystemResources.php#L55
