### ISSUE TITLE
Incompatibility with https://github.com/PHPJunior/nova-logs

### ISSUE THREAD

**Issue by wemersonrv** [GijsGoudzwaard/nova-system-resources#16]
System Resources stop working when app has the package **[Nova Logs](https://github.com/PHPJunior/nova-logs)** installed. I thing is something about compatibility...

Working with Laravel 6.0., and Nova 2.3.0 Windows/Linux servers with NGINX

**Comment by GijsGoudzwaard** [comment]
Could you post the error you are receiving?

**Comment by wemersonrv** [comment]
Hi. nothing... that's the problem. See:

![image](https://user-images.githubusercontent.com/2028673/64912661-c1a46f00-d708-11e9-9b4e-4ed27e860d9a.png)

The cards just stop working.

**Comment by GijsGoudzwaard** [comment]
Could you check your `laravel.log` or the errors posted in the network tab of the developer tools? Or is it maybe a javascript error?

**Comment by wemersonrv** [comment]
Hi. don't have any information in logs... 

In dev tools, console tab i have this:
![image](https://user-images.githubusercontent.com/2028673/64974116-9ba2da00-d882-11e9-9e18-9fbfae709518.png)

In network tab, **systemResources** returns a javascript code...

**Comment by wemersonrv** [comment]
Hello it's me again.

I think this is a problem with Nova Logs package, not with your package.

The problem is when a package causes problem in javascript, other packages that uses javascript crashes too...There is a way to avoid this kind of issue ?!

**Comment by GijsGoudzwaard** [comment]
If there is a problem with Nova Logs, you could try including this package before that package in your NovaServiceProvider. That way this package is allowed to boot before any problems occur.

**Comment by wemersonrv** [comment]
> If there is a problem with Nova Logs, you could try including this package before that package in your NovaServiceProvider. That way this package is allowed to boot before any problems occur.

Ok, understand. Tx.

**Comment by GijsGoudzwaard** [comment]
Closing for now. Feel free to re-open if this problem persists after changing the order.

**Comment by aliwesome** [comment]
@GijsGoudzwaard I've changed the order of use. but the problem still exists.

**Comment by aliwesome** [comment]
@wemersonrv I wonder how you found out the conflict? and what exactly it is to find the best approach.

**Comment by GijsGoudzwaard** [comment]
@aliwesome Please show your laravel log error. Without further information I can't help with your issue.

**Comment by aliwesome** [comment]
There's no error log for laravel. only dev console error logs as below.
![image](https://user-images.githubusercontent.com/21131502/118359880-a69f9780-b59a-11eb-96ce-fcaa485e84ea.png)

**Comment by GijsGoudzwaard** [comment]
Since this is an issue with the Nova logs package you should refer to their issue page. It looks like there is already an open issue on that repository about this problem: https://github.com/PHPJunior/nova-logs/issues/11
