### ISSUE TITLE
Incompatibility with Deployer

### ISSUE THREAD

**Issue by ryryan** [GijsGoudzwaard/nova-system-resources#22]
It seems that this package is not compatible with [Deployer](https://github.com/deployphp/deployer). When used with the Laravel recipe, it  returns this error on the destination server.
```
`> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:
                                                               
  Class 'GijsG\SystemResources\CardServiceProvider' not found  
                                                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1`
```
Running `composer install` or `update` on the /current symlink also returns this error.
Only removing it resolves the issue. Tried clearing route cache, config cache, `composer dump-autoload`

**Comment by GijsGoudzwaard** [comment]
Did you manage to get other nova packages to work with deployer?

**Comment by GijsGoudzwaard** [comment]
Seeing that you've got multiple issues open regarding this problem, I'm going to close this issue. Feel free te re-open if you have more information about why this is an issue with this package.
