### ISSUE TITLE
time scale: "time.format" is deprecated. Please use "time.parser" instead

### ISSUE THREAD

**Issue by authanram** [GijsGoudzwaard/nova-system-resources#26]
To reproduce open the browser console while the polling is active. Nothing else required.

![Screenshot 2020-05-16 at 14 13 31](https://user-images.githubusercontent.com/1874088/82119515-8cf92380-977f-11ea-96f6-3fc77d94c3a2.png)

Maybe i can have a look the days. Hope so.

**Comment by GijsGoudzwaard** [comment]
I'm currently pretty busy with school work, so it would be great if you could take a look!

**Comment by GijsGoudzwaard** [comment]
Available in `1.0.5`
