### ISSUE TITLE
Getting div by zero issue from Sentry in prod server.

### ISSUE THREAD

**Issue by torrancemiller** [GijsGoudzwaard/nova-system-resources#6]
Check out the error, occurring over 1200 times just this morning, on Sentry:

https://sentry.io/share/issue/bbb6c77efaff485e98b855a501003a1b/

Thanks,
-Tor Miller

**Comment by GijsGoudzwaard** [comment]
Could you provide some more information? Like what Linux distribution you use and does it support `free`?

**Comment by GijsGoudzwaard** [comment]
What version of OS X are you running? Could you run `ps -caxm -orss= | awk '{ sum += $1 } END { print sum/1024 }'` in your terminal and paste the output here? Also `hostinfo | grep 'Primary memory available:'`

**Comment by torrancemiller** [comment]
Running standard Forge image of ubuntu:
`Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-21-generic x86_64)`

Getting the following in terminal:
`error: must set personality to get -x option

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
0`

And:
`hostinfo: command not found`

**Comment by GijsGoudzwaard** [comment]
According to Sentry the Mac adapter is being used. Could you see what the output of `PHP_OS` is? Also could you check the output of `php_uname()`? According to php.net `PHP_OS` should return the OS of the system that runs the PHP application but in your case it doesn't

**Comment by GijsGoudzwaard** [comment]
Due to inactivity i assume this is no longer a problem, closing.
